#define SAMPLE_HEALTH 100
#define SAMPLE_POWER 100
#define SAMPLE_PRICE 75
#define SAMPLE_HEALTH_INCREASE 50
#define SAMPLE_POWER_INCREASE 50

#define THREE_COLUMN_HEALTH 200
#define THREE_COLUMN_POWER 300
#define THREE_COLUMN_PRICE 50
#define THREE_COLUMN_HEALTH_INCREASE 50
#define THREE_COLUMN_POWER_INCREASE 100

#define DOUBLE_LIFE_HEALTH 100
#define DOUBLE_LIFE_POWER 0
#define DOUBLE_LIFE_PRICE 50
#define DOUBLE_LIFE_HEALTH_INCREASE 100
#define DOUBLE_LIFE_POWER_INCREASE 0

#define THREE_ROW_HEALTH 10
#define THREE_ROW_POWER 50
#define THREE_ROW_PRICE 150
#define THREE_ROW_HEALTH_INCREASE 50
#define THREE_ROW_POWER_INCREASE 50

#define SLOW_DOWN_HEALTH 50
#define SLOW_DOWN_POWER 100
#define SLOW_DOWN_PRICE 100
#define SLOW_DOWN_HEALTH_INCREASE 25
#define SLOW_DOWN_POWER_INCREASE 50

#define ROBOT_MAX_SPEED 10
#define ROBOT_MIN_SPEED 5
