#pragma once

#define ROWS 5
#define COLUMNS 10
#define FRAME_COLUMNS 6

#define FLUTE_DEFAULT_HEALTH 100
#define FLUTE_DEFAULT_POWER 100
#define FLUTE_UPDATE_PRICE 75
#define FLUTE_HEALTH_INCREASE 50
#define FLUTE_POWER_INCREASE 50

#define DRUM_DEFAULT_HEALTH 200
#define DRUM_DEFAULT_POWER 300
#define DRUM_UPDATE_PRICE 50
#define DRUM_HEALTH_INCREASE 50
#define DRUM_POWER_INCREASE 100

#define SAXOPHONE_DEFAULT_HEALTH 100
#define SAXOPHONE_DEFAULT_POWER 0
#define SAXOPHONE_UPDATE_PRICE 50
#define SAXOPHONE_HEALTH_INCREASE 100
#define SAXOPHONE_POWER_INCREASE 0

#define TRUMPET_DEFAULT_HEALTH 10
#define TRUMPET_DEFAULT_POWER 50
#define TRUMPET_UPDATE_PRICE 150
#define TRUMPET_HEALTH_INCREASE 50
#define TRUMPET_POWER_INCREASE 50

#define VIOLIN_DEFAULT_HEALTH 50
#define VIOLIN_DEFAULT_POWER 100
#define VIOLIN_UPDATE_PRICE 100
#define VIOLIN_HEALTH_INCREASE 25
#define VIOLIN_POWER_INCREASE 50

#define NORMIE music_enum::normie
#define THREE_C music_enum::three_c
#define DOUBLE_L music_enum::double_l
#define THREE_R music_enum::three_r
#define SLOW music_enum::slow

#define ROBOT_MAX_SPEED 32
#define ROBOT_MIN_SPEED 20
